### ISSUE TITLE
Htaccess rewrite module not working 

### ISSUE THREAD

**Issue by sulaiman35** [e404/htaccess-for-nginx#10]
Hi Team,

I have installed nginx with luajit for htaccess redirection but its not working , here is the .htaccess rule which I want to run

```
RewriteEngine on

RewriteCond %{REQUEST_URI}  ^/redirect_frame/snai.html$
RewriteCond %{QUERY_STRING} ea=streaming
RewriteRule (.*) http://www.google.com? [R=301,L]
```

**Comment by e404** [comment]
It is hard to guess what went wrong. Can be a setup issue or something wrong with the script. Can you provide some log output for debugging?

**Comment by rkaiser0324** [comment]
In testing I do see different behavior from Apache if you navigate to `/redirect_frame/snai.html?ea=streaming` so that may be the "not working" you are referring to.

In Apache, this rule matches and you redirect to google.com.  However in nginx the first RewriteCond does not match, because in `replace_server_vars()` it is matching off `request_uri` which has the query string appended in https://github.com/e404/htaccess-for-nginx/blob/cdc41871db1b7fe30e055dabadcbce8c97d8e327/htaccess.lua#L89. 

@e404 shouldn't the `request_uri` variable leave off the query string to match the Apache behavior?

**Comment by rkaiser0324** [comment]
OK I will work on a PR.
